---
title: "RWorksheet_Celestra#4a"
author: "Kenneth Celestra"
date: "2024-10-16"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

1. 
```{r}
HouseHoldData <- data.frame (
  ShoeSize = c(6.5, 9.0, 8.5, 8.5, 10.5, 7.0, 9.5, 9.0, 13.0, 7.5, 10.5, 8.5, 12.0, 10.5, 13.0, 11.5, 8.5, 5.0, 10.0, 6.5, 7.5, 8.5, 10.5, 8.5, 10.5,  11.0, 9.0, 13.0),
  
  Height = c(66.0, 68.0, 64.5, 65.0, 70.0, 64.0, 70.0, 71.0, 72.0, 64.0, 74.5, 67.0, 71.0, 71.0, 77.0, 72.0, 59.0, 62.0, 72.0, 66.0, 64.0, 67.0, 73.0, 69.0, 72.0, 70.0, 69.0, 70.0),
  
  Gender = c("F", "F", "F", "F","M", "F", "F", "F","M","F","M","F","M","M", "M", "M", "F", "F", "M", "F", "F","M", "M", "F","M","M", "M", "M")
)

HouseHoldData
```
a. The data shows that it has three columns namely, shoesize, height and, gender with 28 rows.


b. 
```{r}
s <- subset(HouseHoldData, Gender == "M" & ShoeSize&Height)
s

s2 <- subset(HouseHoldData, Gender == "F" & ShoeSize&Height)
s2
```
c. 
```{r}

sm <- mean(HouseHoldData$ShoeSize)
sm

hm <- mean(HouseHoldData$Height)
hm
```
d. No, because there are some respondents that is taller but has smaller shoe size than others who are shorter.

2. 
```{r}
months_vector <- c("March", "April", "January", "November", "January", "September", "October", "September", "November", "August", "January", "November", "November", "February", "May", "August", "July","December", "August", "August", "September", "November", "February", "April")

factor_months_vector <- factor(months_vector)

factor_months_vector
```
3. Yes, they are both useful because it shows the length, class, mode, and the number of repetitions of the character of two vectors.
```{r}
summary(months_vector)
summary(factor_months_vector)
```
4. 
```{r}
direction <- c("East", "West", "North")

frequency <- c(1, 4, 3)

factor_data <- direction
new_order_data <- factor(factor_data, levels = c("East", "West", "North"))

new_order_data



```
5. a.
```{r}
import_march <- read.table("import_march.csv", header = TRUE, sep =",")

```

b. 
```{r}
import_march
```
6
a.
```{r}
 
  num <-readline(prompt = "Please select a number between 1 and 50: ")
  
  
  if (num < 1 || num > 50) {
    print("The number selected is beyond the range of 1 to 50")
  } else if (num == 20) {
    print("TRUE")
  } else {
    print(num)
  }
```
7
a.
```{r}
  bills <- c(1000, 500, 200, 100, 50)
  numbills <- 0
  
  snackprice <- as.integer(readline(prompt = "Enter the price of the snack (divisible by 50): "))
  
  for (i in bills) {
    if (!is.na(snackprice) && !is.na(i) && snackprice >= i) {
      count <- snackprice %/% i
      numbills <- numbills + count
      snackprice <- snackprice %% i
    } 
  }
paste("Minimum number of bills needed:", numbills)
```
8
a.
```{r}
df <- data.frame(
  Name = c("Annie", "Thea", "Steve", "Hanna"),
  Grade1 = c(85, 65, 75, 95),
  Grade2 = c(65, 75, 55, 75),
  Grade3 = c(85, 90, 80, 100),
  Grade4 = c(100, 90, 85, 90)
)
print(df)

```
b.
```{r}
for (i in 1:nrow(df)) {
  total <- df$Grade1[i] + df$Grade2[i] + df$Grade3[i] + df$Grade4[i]
  avg <- total / 4
  
 if (avg > 90) {
    print(paste(df$Name[i], "'s average grade this semester is", round(avg, 2)))
 } 
}
```
c.
```{r}
grades <- df[, 2:5]
testavg <- colSums(grades) / nrow(grades)

for (i in 1:length(testavg)) {
  if (testavg[i] < 80) {
    print(paste("The", i,"th test was difficult."))
  }
}

```
d.
```{r}

for (i in 1:nrow(df)) {
  highest <- df$Grade1[i]
  
  if (df$Grade2[i] > highest) {
    highest <- df$Grade2[i]
  }
  if (df$Grade3[i] > highest) {
    highest <- df$Grade3[i]
  }
  if (df$Grade4[i] > highest) {
    highest <- df$Grade4[i]
  }
  
  if (highest > 90) {
    print(paste(df$Name[i], "'s highest grade this semester is", highest))
  }
}

```

