---
title: "Worksheet1"
author: "Kenneth Celestra"
date: "2024-09-04"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

1.
a. 34 data points
b.
```{r}
age <- c(34, 28, 22, 36, 27, 18, 52, 39, 42, 29, 35, 31, 27, 22, 37, 34, 19, 20, 57, 49, 50, 37, 46, 25, 17, 37, 42, 53, 41,51, 35, 24, 33, 41)
```
```{r}
length(age)
```
2. 
```{r}
rec <- 1 / age
```

```{r}
library(MASS)
fractions(rec)
```
3.
the vector from age stores twice in new age with a 0 in the middle
```{r}
new_age <- c(age, 0, age)
```
4. 
```{r}
sort(age)
```
5.
```{r}
max(age)
min(age)
```
6.
a. 12 data points
b
```{r}
vec <- c(2.4, 2.8, 2.1, 2.5, 2.4, 2.2, 2.5, 2.3, 2.5, 2.3, 2.4, 2.7)
```
7. the values inside the vector doubled
```{r}
double <- vec * 2
```
```{r}
double
```
8.1
```{r}
hundred <- seq(1:100)
```
8.2
```{r}
nums <- seq(20, 60)
```
8.3
```{r}
m <- mean(nums)
```
8.4 
```{r}
s <- sum(51:91)
```
8.5
```{r}
thousand <- seq(1:1000)
```
a. 143 data points
b.
```{r}
length(hundred) + length(nums) + length(m) + length(s)
```
c.
```{r}
max(thousand[thousand <- 10])
```


9.
```{r}
Filter(function(i) { all(i %% c(3,5,7) != 0) }, seq(100))
```
10.
```{r}
back <- seq(100,1)
back
```
11.
a. 136 data points
b.
```{r}
numbers <- 1:24
multiples <- numbers[numbers %% 3 == 0 | numbers %% 5 == 0]
sum_multiples <- sum(multiples)

```
a. 
```{r}
length(back) + length(numbers) + length(multiples) + length(sum_multiples)
```
12. it shows an error unexpected '}'
```{r}
#x <- {0 + x + 5 + }

```
13. 
```{r}
score <- c(72, 86, 92, 63, 88, 89, 91, 92, 75, 75, 77)
score[2]
score[3]
```
14.
```{r}
a = c(1,2,NA,4,NA,6,7)
```
a.
```{r}
print(a,na.print="-999")
```
b. with na.print it replaces all NA on the previous vector to -999

15.
```{r}
name = readline(prompt="Input your name: ")
age = readline(prompt="Input your age: ")
print(paste("My name is",name, "and I am",age ,"years old."))
print(R.version.string)
```
It asks me for my name and age and prints it




















